[tools]
gh = "latest"
java = "corretto-20.0.2.10.1"
node = "latest"
peco = "latest"
python = "3.11"
usage = "latest"
uv = "latest"
yq = "latest"
ty = "latest"
ruff = "latest"
ghq = "latest"
rg = "latest"
fzf = "latest"
chezmoi = "latest"
markdownlint-cli2 = "latest"
fd = "latest"
stylua = "latest"
lua-language-server = "latest"

[shell_alias]
pr = "gh pr view --web"
prr = "gh pr ready"

[settings]
experimental = true

